# Generated by Django 2.1.7 on 2019-05-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRankCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('difficulty_score', models.FloatField(default=0)),
                ('funny_score', models.FloatField(default=0)),
                ('gain_score', models.FloatField(default=0)),
                ('recommend_score', models.FloatField(default=0)),
                ('position', models.FloatField(default=-1)),
                ('people', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateMyCourse.Teacher')),
            ],
        ),
    ]
