# Generated by Django 2.1.7 on 2019-04-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateMyCourse.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateMyCourse.Department')),
                ('user', models.ManyToManyField(to='rateMyCourse.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
