# Generated by Django 2.1.7 on 2019-05-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0002_auto_20190430_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateMyCourse.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateMyCourse.User')),
            ],
        ),
        migrations.RenameField(
            model_name='rankcache',
            old_name='total_position',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='rankcache',
            name='difficulty_position',
        ),
        migrations.RemoveField(
            model_name='rankcache',
            name='funny_position',
        ),
        migrations.RemoveField(
            model_name='rankcache',
            name='gain_position',
        ),
        migrations.RemoveField(
            model_name='rankcache',
            name='recommend_position',
        ),
    ]
