# Generated by Django 2.1.7 on 2019-05-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyCourse', '0003_auto_20190504_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankcache',
            name='people',
            field=models.IntegerField(default=0),
        ),
    ]
